### PR TITLE
Add Avatar file uploader

### PR DESCRIPTION
**Pull request by ninjadevtrack**

### CODE REVIEW

**Comment by prologic** [comment]
Also as an aside, please practice good Git hygiene, and rebase your branch properly on master as opposed to "git merge master" into your branch. I much prefer to keep linear history even across feature features where possible. Thanks :)

**Comment by prologic** [comment]
ping?!

**Comment by ninjadevtrack** [comment]
> ping?!

I have almost done. But I don't understand why I need to make SCSS changes to picocss.

**Comment by prologic** [comment]
> > ping?!
> 
> I have almost done. But I don't understand why I need to make SCSS changes to picocss.

Because the project uses a [forked version](https://github.com/prologic/picocss) that is built from SCSS source?

Also why did you close this PR? Accident? If you're nearly done please commit the changes to this branch so we can test/review  and merge them!

**Pull request closed without merging**
