### PR TITLE
Add support for syndication formats (RSS, Atom, JSON Feed)

### PR DESCRIPTION
**Pull request by prologic**
##### Summary

ssia

##### Component Name

- area/backend

##### Test Plan

<details>
<summary>/feed.json</summary>

```#!json
{
  "version": "https://jsonfeed.org/version/1",
  "title": "admin Twtxt",
  "home_page_url": "http://0.0.0.0:8000/user/admin",
  "author": {
    "name": "admin"
  },
  "items": [
    {
      "id": "",
      "url": "http://0.0.0.0:8000/#s%!(EXTRA func() string=0x1627a80)",
      "title": "Hello World",
      "date_published": "2020-08-07T19:34:02.995438+10:00",
      "author": {
        "name": "admin"
      }
    },
    {
      "id": "",
      "url": "http://0.0.0.0:8000/#s%!(EXTRA func() string=0x1627a80)",
      "title": "Hello World",
      "date_published": "2020-08-07T19:34:02.995438+10:00",
      "author": {
        "name": "admin"
      }
    }
  ]
}
```
</details>

<details>
<summary>/rss.xml</summary>

```#!xml
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/">
  <channel>
    <title>admin Twtxt</title>
    <link>http://0.0.0.0:8000/user/admin</link>
    <description></description>
    <managingEditor> (admin)</managingEditor>
    <pubDate>Fri, 07 Aug 2020 19:35:07 +1000</pubDate>
    <item>
      <title>Hello World</title>
      <link>http://0.0.0.0:8000/#s%!(EXTRA func() string=0x1627a80)</link>
      <description></description>
      <author>admin</author>
      <pubDate>Fri, 07 Aug 2020 19:35:07 +1000</pubDate>
    </item>
    <item>
      <title>Hello World</title>
      <link>http://0.0.0.0:8000/#s%!(EXTRA func() string=0x1627a80)</link>
      <description></description>
      <author>admin</author>
      <pubDate>Fri, 07 Aug 2020 19:35:07 +1000</pubDate>
    </item>
  </channel>
</rss>
```
</details>

<details>
<summary>/atom.xml</summary

```#!xml
<?xml version="1.0" encoding="UTF-8"?><feed xmlns="http://www.w3.org/2005/Atom">
  <title>admin Twtxt</title>
  <id>http://0.0.0.0:8000/user/admin</id>
  <updated>2020-08-07T19:35:49+10:00</updated>
  <link href="http://0.0.0.0:8000/user/admin"></link>
  <author>
    <name>admin</name>
  </author>
  <entry>
    <title>Hello World</title>
    <updated>2020-08-07T19:35:49+10:00</updated>
    <id>tag:http://0.0.0.0:8000/#s%!(EXTRA func() string=0x1627a80),2020-08-07:/invalid.html</id>
    <link href="http://0.0.0.0:8000/#s%!(EXTRA func() string=0x1627a80)" rel="alternate"></link>
    <summary type="html"></summary>
    <author>
      <name>admin</name>
    </author>
  </entry>
  <entry>
    <title>Hello World</title>
    <updated>2020-08-07T19:35:49+10:00</updated>
    <id>tag:http://0.0.0.0:8000/#s%!(EXTRA func() string=0x1627a80),2020-08-07:/invalid.html</id>
    <link href="http://0.0.0.0:8000/#s%!(EXTRA func() string=0x1627a80)" rel="alternate"></link>
    <summary type="html"></summary>
    <author>
      <name>admin</name>
    </author>
  </entry>
</feed>
```
</details>

##### Additional Information

- Cloese #94

### CODE REVIEW

**Comment by prologic** [comment]
cc @fluffy-critter

**Comment by fluffy-critter** [comment]
I don't know enough about twtxt's internals to review the code which is there but I do have two comments based on skimming this:

1. Does twtxt support boosting others' posts? If so, boosted posts would benefit from having a `<source>` element in the atom feed
2. It's useful to add appropriate feed discovery `<link>`s to the user profile pages so that people would be able to subscribe to the feed without knowing how to form the feed URL. And, I would still highly recommend making user profiles publicly (ie without logging in) visible by default so that there's a natural place to put these links that doesn't require that people log in to follow someone.

**Comment by prologic** [comment]
> Does twtxt support boosting others' posts? If so, boosted posts would benefit from having a <source> element in the atom feed

No.

> It's useful to add appropriate feed discovery <link>s to the user profile pages so that people would be able to subscribe to the feed without knowing how to form the feed URL. And, I would still highly recommend making user profiles publicly (ie without logging in) visible by default so that there's a natural place to put these links that doesn't require that people log in to follow someone.

I added support for open profiles in 926b988 I just haven't configured the [twtxt.net](https://twtxt.net) pod yet with this option. Is there any reason _not_ to have open profiles? I'm just thinking out loud here as we also want to support pseduo-private pods down the track.

**Comment by fluffy-critter** [comment]
Hmm, I think it depends on the goal of pseudo-private pods. I think that in the case of someone wanting their profile to be totally private, they probably wouldn't want random people subscribing via rss/atom anyway, so having an open profile becomes less important, aside from the impact it would have on IndieWeb integration.

Basically, with IndieWeb there *must* be at least some sort of publicly-visible page that declares the user's various endpoints (indieauth, micropub, etc.) and there *should* be a publicly-visible `h-card` for other sites to consume. Outgoing webmention also requires that the post itself be visible to the recipient's webmention endpoint, and incoming webmention needs to at least have the webmention endpoint visible on whatever's being mentioned (such as the user's profile or the individual post).

Distributed privacy is a giant mess in this world and there's a few separate initiatives to try to improve things, but there's just a couple of rough proofs-of-concept and random articles floating out there and no specific "here is what you should do" guidance just yet. That said, the most promising effort is described here: https://indieweb.org/IndieAuth_Ticket_Auth (but it still assumes that the user's profile page is visible, even if the posts themselves aren't).

**Comment by prologic** [comment]
Thanks for your comments and explanation! Really helpful!

One last thing; I'm not convinced we should provide all 3 forms of "syndication formats". What do you think? They're basically the same :)

**Comment by fluffy-critter** [comment]
> One last thing; I'm not convinced we should provide all 3 forms of "syndication formats". What do you think? They're basically the same :)

Yeah personally I think there's only a reason to provide Atom, which I think I said earlier. :) Atom is a strict superset of RSS, and basically nobody uses JSON Feed.

**Comment by prologic** [comment]
Okay this has been deployed to [twtxt.net](https://twtxt.net) now. Have also reconfigured the pod to have open profiles.

```
twtxt_twtxt.1.s8ue3pok01r7@c1dm3    | time="2020-08-08T02:02:16Z" level=info msg="Open User Profiles: true"
```

**Pull request merged**
