### PR TITLE
Add documentation on using docker-compose

### PR DESCRIPTION
**Pull request by flavienbwk**
Additionaly, removed the `data` directory.

Related to #18

### CODE REVIEW

**Comment by prologic** [comment]
@flavienbwk Can you fix this PR or would you like me to cherry-pick your changes?

**Comment by flavienbwk** [comment]
@prologic Here you have it

**Comment by prologic** [comment]
> @prologic Here you have it

Do you mind undoing the deletions of `./data/...` Please and I'll merge 👍

**Comment by flavienbwk** [comment]
Oops, thought I readded it.

**Pull request merged**
