### PR TITLE
#18 : Adding proper Docker architecture for runtime

### PR DESCRIPTION
**Pull request by flavienbwk**
- Edited Docker architecture accordingly to #18 
- Updated README.md to remove annoying `$`  signs for commands and including a section on how to lauch the Docker container

### CODE REVIEW

**Comment by flavienbwk** [comment]
Conflicts are due to the facts the updated Docker architectures sets all the source code in an `src/`directory

**Comment by prologic** [comment]
Hmmm 🤔 WOW 😲 Big PR here! I normally don't write Go code like this with all the source in a `./src` directory. I'd have gone with an `internal` package or other sub-packages before I even attempted to just move the source away from the top-level directory. What's the advantages of moving the source to `./src`? Are there any downsides you're aware of?

**Comment by prologic** [comment]
Also can you fix the conflicts so I can check this PR out locally and make sure things still work as expected :)

**Comment by flavienbwk** [comment]
> Hmmm  WOW  Big PR here! I normally don't write Go code like this with all the source in a `./src` directory. I'd have gone with an `internal` package or other sub-packages before I even attempted to just move the source away from the top-level directory. What's the advantages of moving the source to `./src`? Are there any downsides you're aware of?

I understand. I am not really familiar with Go so I guess you have a better idea about packaging the project. As explained in #18, what we want to absolutely avoid is a `COPY . .` line in the Dockerfile, re-building everytime ALL the project even if one character changed in the README. This is why I moved the sources to `src/`.

**Comment by flavienbwk** [comment]
I am not sure about where to edit the test and build CI rules to point to `src/`, could you tell me where I can edit them ?

**Comment by flavienbwk** [comment]
I may need help with why the CI fails @prologic (seems to be Go-related)

**Comment by prologic** [comment]
Yes I suspect its because you've effectively broken all the imports :)

Thanks for fixing the conflicts, I'll check this out locally and improve upon what you've done and push some commits to your branch. Hope its okay that we _may_ not use ` ./src` but maybe I'll move most/all of the sources to `./internal` instead.

Basically the top-level is actually the `github.com/prologic/twtxt` import path, so moving the code somewhere else breaks all the imports.

**Comment by prologic** [comment]
Hmmm just checked our your PR locally. This actually breaks basically everything :/ 🤔

**Comment by prologic** [comment]
Can we make the `Dockerfile` something like this:

```#!Dockerfile
# Build
FROM golang:alpine AS build

RUN apk add --no-cache -U build-base git make

RUN mkdir /src

WORKDIR /src

# Copy Makefile
COPY Makefile /src/

# Copy go.mod and go.sum and install and cache dependencies
COPY go.mod go.sum /src/

# Install deps
RUN make deps

# Copy static assets
COPY static /src

# Copy templates
COPY templates /src

# Copy sources
COPY *.go /src/

# Build binary
RUN make build

# Runtime
FROM alpine:latest

RUN apk --no-cache -U add ca-certificates

WORKDIR /
VOLUME /data

COPY --from=build /src/twtd /twtd

ENTRYPOINT ["/twtd"]
CMD [""]
```

This _almost_ works but I'm having problems copying the `static` and `templates` to the Docker context properly.

**Comment by prologic** [comment]
@flavienbwk Do you think we could go with the approach in #20 ? It has the same idea and I tested that the Docker build cache isn't invalidated when just changing say the `README.md` (_in fact it is no longer copied to the Docker context as its not required_).

The only things missed from #20 are:

- Your `docker-compose.yml` which I'd like to have a closer look at; because I in fact do have my own as well that I haven't published yet that powers https://twtxt.net/ -- However I usually run Docker Swarm clusters; so my `twtxt.yaml` also includes Docker Compose v3.8 syntax and Swarm labels, etc
- Missing the `.git` directory and therefore isn't able to correctly version the binary. This _could_ be solved differently perhaps by passing `--build-argVERSION` and `--build-argCOMMIT` arguments to `docker build`.

**Comment by flavienbwk** [comment]
I really like the idea of #20. I even prefer it because it specifies exactly the files that are copied in the container. Plus it solves the dependencies issue. 

Perfect for the compose with Swarm, it's a good idea and allows people not using swarm to deploy with compose anyway.

**Comment by flavienbwk** [comment]
I think you can close this merge request in favor of yours!

**Pull request closed without merging**
