### PR TITLE
Add user profile pages and **BREAKS** existing local user feed URIs

### LINKED ISSUE #15: [BREAKING CHANGE]: Profile page vs. Twtxt feed URL?
I'm _thinking_ of potentially changing a key important critical feature of `twtxt` and on the hosted instance https://twtxt.net/ that would break existing feeds there and anyone else that has since spun up their own instance.

Basically I'm _thining_ about this:

> Should https://twtxt.net/u/prologic by a "sort of" Profile page for me?
> (_There is no Personal Identifiable Information / PII that `twtxt` stores at this time but it _might_ be a useful feature one day?_)

If we decide to do this I would change the Twtxt feed URIs to match those of [rss2twtxt](https://github.com/prologic/rss2twtxt) over at https://feeds.twtxt.net/feeds

Now is the time to do it while the usage and no. of `twtxt` is low. Comments?

### PR DESCRIPTION
**Pull request by prologic**
Closes #15

This does a few things here:

- Adds user profile pages for local uses. e.g: https://twtxt.netu/prologic
- **BREAKS** the existing local user `twtxt` feed URIs to now be https://twtxt.net/u/prologic/twtxt.txt
- Adds some pretty icons around a few places (_because why not!_)

### CODE REVIEW

**Comment by prologic** [comment]
@lwojcik Would you be able to test this PR as well? I _believe_ everything works as expected.

**Comment by prologic** [comment]
@lwojcik I don't _want _ to rush you; but do you think you could check this branch our, build it and have a play and drop me some feedback so I can merge this sooner than a week? Given the uptake and interest in this [twtxt.net](https://twtxt.net) I'd rather break this particular sensitive change sooner than later :)

**Comment by prologic** [comment]
if it helps I can put up another instance for this branch somewhere if that helps -- with empty data.

**Comment by lwojcik** [comment]
Yeah, I'll do that this weekend.

**Comment by prologic** [comment]
@lwojcik Do you mind approving this PR? :)

**Comment by lwojcik** [comment]
Done and done. :)

**Pull request merged**
